In [2]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
np.array([x[0:, 0], x[0:, 1]])

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [17]:
np.random.randint(0, 4, 3)

array([0, 3, 0])

In [24]:
x = np.array([0, 14, 22, 35, 43, 56, 66, 72, 84, 97])
x[[1, 2]]

array([14, 22])

In [7]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(x)

x[0:2, 2:] = 0
x[2:, 0:2] = 0
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  0  0]
 [ 5  6  0  0]
 [ 0  0 11 12]
 [ 0  0 15 16]]


In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [5, 6], [5, 6]])
print(np.concatenate((a, b), axis=0))
print(np.append(a, b, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]


In [20]:
a = np.array([[1, 2, 12, 21], [3, 4, 34, 43]])
print(a)
a.transpose()

[[ 1  2 12 21]
 [ 3  4 34 43]]


array([[ 1,  3],
       [ 2,  4],
       [12, 34],
       [21, 43]])

In [28]:
x = np.ones((3,4))
y = np.zeros((3,4))
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)


(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]]))

In [37]:
np.ones((3,1)) + np.zeros((1,30))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
A = np.arange(20).reshape(5, 4)

In [44]:
sum_A = A.sum(axis=1, keepdims=True)
print(A)
sum_A

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [6]:
np.inf - np.inf


nan